[2022-07-31 15:19:01,948] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies.get_sklearn scheduled__2022-05-29T00:00:00+00:00 [queued]>
[2022-07-31 15:19:01,967] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies.get_sklearn scheduled__2022-05-29T00:00:00+00:00 [queued]>
[2022-07-31 15:19:01,967] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 15:19:01,967] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-31 15:19:01,968] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 15:19:01,997] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_sklearn> on 2022-05-29 00:00:00+00:00
[2022-07-31 15:19:02,003] {standard_task_runner.py:52} INFO - Started process 8178 to run task
[2022-07-31 15:19:02,007] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies', 'get_sklearn', 'scheduled__2022-05-29T00:00:00+00:00', '--job-id', '731', '--raw', '--subdir', 'DAGS_FOLDER/DAGWithPythonDependencies.py', '--cfg-path', '/tmp/tmpy0lj6_rt', '--error-file', '/tmp/tmp209wu2up']
[2022-07-31 15:19:02,008] {standard_task_runner.py:80} INFO - Job 731: Subtask get_sklearn
[2022-07-31 15:19:02,103] {task_command.py:369} INFO - Running <TaskInstance: dag_with_python_dependencies.get_sklearn scheduled__2022-05-29T00:00:00+00:00 [running]> on host 4688dd3b7141
[2022-07-31 15:19:02,248] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yosr
AIRFLOW_CTX_DAG_ID=dag_with_python_dependencies
AIRFLOW_CTX_TASK_ID=get_sklearn
AIRFLOW_CTX_EXECUTION_DATE=2022-05-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-29T00:00:00+00:00
[2022-07-31 15:19:02,250] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/DAGWithPythonDependencies.py", line 15, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2022-07-31 15:19:02,280] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies, task_id=get_sklearn, execution_date=20220529T000000, start_date=20220731T151901, end_date=20220731T151902
[2022-07-31 15:19:02,304] {standard_task_runner.py:97} ERROR - Failed to execute job 731 for task get_sklearn (No module named 'sklearn'; 8178)
[2022-07-31 15:19:02,348] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-31 15:19:02,427] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
