[2022-07-30 23:17:10,067] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2022-05-11T00:00:00+00:00 [queued]>
[2022-07-30 23:17:10,089] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2022-05-11T00:00:00+00:00 [queued]>
[2022-07-30 23:17:10,089] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-30 23:17:10,089] {taskinstance.py:1357} INFO - Starting attempt 6 of 6
[2022-07-30 23:17:10,089] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-30 23:17:10,113] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-05-11 00:00:00+00:00
[2022-07-30 23:17:10,123] {standard_task_runner.py:52} INFO - Started process 2780 to run task
[2022-07-30 23:17:10,130] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_postgres_table', 'scheduled__2022-05-11T00:00:00+00:00', '--job-id', '895', '--raw', '--subdir', 'DAGS_FOLDER/DAGWithPostgresOperator.py', '--cfg-path', '/tmp/tmp2l_4aakt', '--error-file', '/tmp/tmp9scypu42']
[2022-07-30 23:17:10,132] {standard_task_runner.py:80} INFO - Job 895: Subtask create_postgres_table
[2022-07-30 23:17:10,218] {task_command.py:369} INFO - Running <TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2022-05-11T00:00:00+00:00 [running]> on host 66bf18ec08cc
[2022-07-30 23:17:10,336] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yosr
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-05-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-11T00:00:00+00:00
[2022-07-30 23:17:10,360] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-07-30 23:17:10,362] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internal " to address: Name or service not known

[2022-07-30 23:17:10,380] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_with_postgres_operator, task_id=create_postgres_table, execution_date=20220511T000000, start_date=20220730T231710, end_date=20220730T231710
[2022-07-30 23:17:10,403] {standard_task_runner.py:97} ERROR - Failed to execute job 895 for task create_postgres_table (could not translate host name "host.docker.internal " to address: Name or service not known
; 2780)
[2022-07-30 23:17:10,428] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-30 23:17:10,563] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
