[2022-07-31 15:19:10,907] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies.get_sklearn scheduled__2022-06-13T00:00:00+00:00 [queued]>
[2022-07-31 15:19:10,934] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies.get_sklearn scheduled__2022-06-13T00:00:00+00:00 [queued]>
[2022-07-31 15:19:10,934] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 15:19:10,934] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-31 15:19:10,934] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 15:19:10,957] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_sklearn> on 2022-06-13 00:00:00+00:00
[2022-07-31 15:19:10,963] {standard_task_runner.py:52} INFO - Started process 8217 to run task
[2022-07-31 15:19:10,966] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies', 'get_sklearn', 'scheduled__2022-06-13T00:00:00+00:00', '--job-id', '746', '--raw', '--subdir', 'DAGS_FOLDER/DAGWithPythonDependencies.py', '--cfg-path', '/tmp/tmp5g59hy9i', '--error-file', '/tmp/tmpdtasf7fm']
[2022-07-31 15:19:10,967] {standard_task_runner.py:80} INFO - Job 746: Subtask get_sklearn
[2022-07-31 15:19:11,084] {task_command.py:369} INFO - Running <TaskInstance: dag_with_python_dependencies.get_sklearn scheduled__2022-06-13T00:00:00+00:00 [running]> on host 4688dd3b7141
[2022-07-31 15:19:11,207] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yosr
AIRFLOW_CTX_DAG_ID=dag_with_python_dependencies
AIRFLOW_CTX_TASK_ID=get_sklearn
AIRFLOW_CTX_EXECUTION_DATE=2022-06-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-13T00:00:00+00:00
[2022-07-31 15:19:11,209] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/DAGWithPythonDependencies.py", line 15, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2022-07-31 15:19:11,226] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies, task_id=get_sklearn, execution_date=20220613T000000, start_date=20220731T151910, end_date=20220731T151911
[2022-07-31 15:19:11,249] {standard_task_runner.py:97} ERROR - Failed to execute job 746 for task get_sklearn (No module named 'sklearn'; 8217)
[2022-07-31 15:19:11,267] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-31 15:19:11,346] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
